package com.flashform.core.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;

@Entity
@Table(name = "submissions")
@Data   // auto-generation for Getter/Setter
@NoArgsConstructor  // auto-generation for no-argument construction public Submission() {}
public class Submission {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated serial number

    private String formId;

    private String userId;

    @Column(columnDefinition = "TEXT")
    private String answersJson; // transform Map into JSON String for storage (simple process)

    private LocalDateTime createTime;

    public Submission(String formId, String userId, String answersJson) {
        this.formId = formId;
        this.userId = userId;
        this.answersJson = answersJson;
        this.createTime = LocalDateTime.now();
    }
}