package com.flashform.core.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "submissions")
public class Submission {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated serial number

    private String formId;

    private String userId;

    @Column(columnDefinition = "TEXT")
    private String answersJson; // transform Map into JSON String for storage (simple process)

    private LocalDateTime createTime;

    // Constructors, Getters, Setters
    public Submission() {}

    public Submission(String formId, String userId, String answersJson) {
        this.formId = formId;
        this.userId = userId;
        this.answersJson = answersJson;
        this.createTime = LocalDateTime.now();
    }

    // 省略 Getter/Setter，請務必補上 (或用 Lombok @Data)
    public Long getId() { return id; }
    public String getFormId() { return formId; }
    public String getUserId() { return userId; }
    public String getAnswersJson() { return answersJson; }
}